spring:
  #  profiles: qrsignin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.136.38:3306/qrsignin2?useSSL=false&useUnicode=true&characterEncoding=utf8
    password: jiubugaosuni
    username: root

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 60000
      validation-timeout: 3000
      connection-timeout: 60000
      idle-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: qrsigninapp
server:
  port: 8082